# permissions for end users to view jobbuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jobbuilder-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobbuilder
    app.kubernetes.io/part-of: jobbuilder
    app.kubernetes.io/managed-by: kustomize
  name: jobbuilder-viewer-role
rules:
- apiGroups:
  - api.job-builder
  resources:
  - jobbuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.job-builder
  resources:
  - jobbuilders/status
  verbs:
  - get
